name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # to overcome a pylint import error, we try to import it inside poetry
      run: |
        python -m pip install --upgrade pip        
        pip install poetry==1.2.0
        cd examiner
        poetry install
    - name: Analysing the code with pylint
      run: |
        cd examiner
        poetry run pylint $(git ls-files '*.py')
