name: Pylint

# Taken from https://github.com/pallets/click/blob/main/.github/workflows/tests.yaml
on:
  push:
    branches:
      - master
      - 'feature/*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
    steps:
    - uses: actions/checkout@v4    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Restore cached env
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: |
          venv/*
        key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        test -d venv || virtualenv venv
        source venv/bin/activate
        pip install poetry==1.2.0        
        poetry install --with dev
    - name: Save venv
      id: cache-save
      uses: actions/cache/save@v4
      with:
        path: |
          venv/*
        key: ${{ steps.cache.outputs.cache-primary-key }}
    - name: Analysing the code with pylint
      run: |
        test -d venv && source venv/bin/activate        
        poetry run pylint --rcfile=./pylint.rc  $(git ls-files '*.py')
